// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAhkXNsp6kbEL3K6dPOkyx_Osb4nhslK0',
    appId: '1:797355089632:android:8ba3609488f89a0f15ba85',
    messagingSenderId: '797355089632',
    projectId: 'voting-system-87e09',
    databaseURL: 'https://voting-system-87e09-default-rtdb.firebaseio.com',
    storageBucket: 'voting-system-87e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFhIAe06SF-a7dFuyNMPTc8M5UjEypZA',
    appId: '1:797355089632:ios:77ad609933243bc015ba85',
    messagingSenderId: '797355089632',
    projectId: 'voting-system-87e09',
    databaseURL: 'https://voting-system-87e09-default-rtdb.firebaseio.com',
    storageBucket: 'voting-system-87e09.appspot.com',
    androidClientId: '797355089632-6bpdgme8g4eb1b49178l5fo85dej33vu.apps.googleusercontent.com',
    iosClientId: '797355089632-css018qrsk43grr1p0gs5q72ffucfrv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.op',
  );
}
